### ISSUE TITLE
Úkoly Python - program 1-5

### ISSUE THREAD

**Issue by zopletalova** [zopletalova/python-012021#1]
Ahoj Andy,
@andywaltlova
odevzdávám úkoly z úterní lekce - aspoň si to myslím :-)
Návod jsem nějak jen rychle prolétla, tak snad je vidíš všechny :-)
Děkuji předem za zpětnou vazbu
Zuzka

**Comment by andywaltlova** [comment]
### 1. úkol :heavy_check_mark:

- řádek 9 - je tam potřeba? :) (o řádek níž si to stejně hned přepíšeš)
- Pokud spojuješ jen takto dvě podmínky, nejsou třeba závorky, samozřejmě pro přehlednost je tam nechat můžeš
- Ve slovníku `baliky` jsou všechny hodnoty datového typu bool, běžně se tedy nedělá, že by si porovnávala `True == True` nebo `False == True`, protože samotná podmínka pracuje přímo s bool hodnotou. V příkladu níže tedy můžeš za `True` vložit jakoukoli proměnnou datového typu bool. [1]

```
pravda =True
if pravda:
    print('Je to pravda')
else:
    print('Neni to pravda')
```

A ano v Pythone existuje konstrukce else if, zkracene `elif`:
```
num = 4
if num > 0 :
    print('kladne')
elif num < 0:
    print('zaporne')
else:
    print('nula')
```
Jinak vnořené podmínku nejsou vždy na škodu, tady v tomto příklady by si například mohla jen jednou kontrolovat zda je cislo ve slovníku a pak vnorit podminku zda je nebo není doručen. 

### 2. úkol :heavy_check_mark:
- opět řádky 9 a 10 zbytečné (nebyla si na Jave? V Pythone není třeba nijak inicializovat proměnné než jim přiřadíš první hodnotu)
- řádek 14 zbytečné závorky, opět podezřívám zkušenost s Javou 
- řádek 23 `sklad[soucastka] - sklad[soucastka]`, neznamená to prostě, že je na skladě nula kusů ? :) 
- Jinak moc pěkné, chválím použití f-strings
- Pokud by jsi chtěla kód úplně vyšperkovat, je možno nahradit například `sklad[soucastka] = sklad[soucastka] - mnozstvi` za zkrácený zápis `sklad[soucastka] -=  mnozstvi` :) ale to je jen doporučení

### 3. úkol :heavy_check_mark:
- zbytečný řádek 8
- Celkově skvělé, super že jsi využila i else větev ikdyž to zadání explicitně nepožaduje :)

### 4. úkol :heavy_check_mark:
- opět řádky navíc (49,50,51)
- Pouze doporučení: trochu by si si usnadila práci pokud by si místo `for i in range()` v cyklu zkrátka procházela string po znacích, nepotřebovala by jsi potom proměnnou `morse`.
- Jinak moc pěkné.
```
for znak in 'hello':
    print(znak, end='')
```
### 5. úkol :heavy_check_mark:
- zbytečné řádky 18, 19 a závorky v ifech :)
- Klíč by měl být unikátní, pokud není, tak platí hodnota, která je uvedena jako poslední, v tomto případě by to byl řádek 13, super, že sis toho všimla :)
- Opět pěkný kód.

***
[1] Dokonce můžeš takto porovnávat i jiné datový typy, můžeš například zkusit zjistit jak vypada` bool(1)`,`bool(0)`,`bool(-1)`, nebo `bool('')` a `bool('hello')`.

Vesměs všechny poznámky jsou spíše k zamyšlení a vyšperkování již tak pěkného kódu, proto tě prosím pouze o opravu prvního úkolu:
- práce s bool hodnotami
- řádek navíc
- úpravu podmínky nechám na tobě, tak jak ti to přijde nejrozumější :)

Skvělá práce, jen tak dál 👍

**Comment by zopletalova** [comment]
Ahoj Andy,
děkuji za připomínky! 👍
- ano, nejspíš se mi tam motá Java, na té jsem z programovacích jazyků byla jako na poslední, tak mi deklarace proměnných asi zůstala v hlavě - a Python se kvůli tomu ani nezlobil... 😀
- jedu pokus - omyl - zkusím, a když funguje, jsem ráda - tudíž moc děkuji za připomínky k možnému zjednodušení a za tipy a vychytávky
- Kromě programu1 jsem dobrovolně upravila i program4 (Morseovka) - nevěděla jsem, že je tak možné string procházet, respektive jsem neznala zápis, chtěla jsem si to zkusit a takto je to určitě lepší!
Ještě jednou moc díky ✌
Zuzka

**Comment by andywaltlova** [comment]
Ahoj,

super, takže máš vše splněno ! :-)

Jinak Python si stěžovat nebude, protože jsi neudělala nic špatného, je to zkrátka jen řádek navíc, který je v kontextu programu zbytečný, protože k ničemu neslouží, ale jeho zápis je syntakticky správně :-) 

Kromě stringu takto jde procházet i seznamy, respektive jde to oběma způsoby protože seznamy i stringy se dají indexovat stejně.

Užij si víkend!

Andy

**Comment by andywaltlova** [comment]
@zopletalova Ještě mě napadlo, pokud by tě zajímalo alternativní řešení třeba příkladu 5. ale dá se to použít na více místech. Tak existuje na slovniku [metoda get](https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey), ktera je hodně podobná zápisu `slovnik[klic]`, ale má jednu výhodu, a to že jí můžeš definovat hodnotu kterou vrátí, pokud klíč ve slovníku nenajde :) Konkretne v prikladu 5, by mohla vracet 0 pokud klic ve slovniku neni :) 

Ale zminuji to spise doplnkove, protoze na uvodních kurzech se nepouziva, ale mohlo by se stat ze by si ji videla, kdyby si neco o slovnikach hledala na internetu :)

**Comment by zopletalova** [comment]
Ahoj Andy
@andywaltlova Děkuji moc - zkusila jsem, funguje :-)
Už dřív mě ještě napadla otázka - dá se ze slovníku nějak vypsat klíč? Nebo rovnou třeba seznam klíčů?
- vím, jak vypsat celý slovník (prostě print(dictionary)) - trochu ošklivý výstup, s těma všema závorkama :-)
- vím, jak vypsat hodnotu na základě zadání klíče
Ale kdybych z toho "dictionary" chtěla chtěla vytáhnout jen klíče? Tedy aby výstup byl "Name" nebo "Age", respektive třeba postupný výpis klíčů - z příkladu, co jsem si zkoušela níže:

dictionary = {"Name": "Harry", "Age": 17}
key = input("Zadejte klíč: ")

print(dictionary)
"""Vypíše celý slovník: {'Name': 'Harry', 'Age': 17}"""

print(dictionary.get(key)) 
"""vrátí None, když klíč neexistuje; když existuje, vypíše hodnotu"""

print(dictionary[key]) 
"""vyhodí chybu, když klíč neexistuje; když existuje, vypíše hodnotu"""
 
Děkuji :-)
Z

**Comment by andywaltlova** [comment]
Ahoj,

ano určitě se dá :) 

V [dokumentaci](https://docs.python.org/3/library/stdtypes.html#mapping-types-dict) je obecně popsano jak slovnik funguje a co se s nim dá vše dělat. 

Nejpoužívanější jsou asi tyto tři metody:
```
dictionary = {"Name": "Harry", "Age": 17}
hodnoty = dictionary.values()
klice = dictionary.keys()
dvojice = dictionary.items()
```
Vsechny tyto metody nevraci primo listy, ale vraci takzvane [view objects](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects), coz te moc nemusi zajimat, protoze jsou to iterovatelne hodnoty stejne jako jsou listy, takze muzes normalne pouzivat operator `in` a stejne tak je for cyklem prochazet. Na vsechny promenne klidne muzes zavolat funkci list() a tim se ty view objekty prevedou na obycejne listy :)

V pristi lekci si v souvislosti s for cykly budeme ukazovat, ze se prave daji prochazet klice a hodnot slovniku najednou.

```
for k,v in dictionary.items():
    print(k,v)
```

**Comment by zopletalova** [comment]
Ahoj Andy
@andywaltlova
moc díky, hodila jsem to "do stroje" a to poslední procházení pomocí cyklu for je přesně to, co jsem hledala 👍 
Ještě jednou děkuji moc a už ti dám pokoj, ať se můžeš věnovat taky ostatním 😎
Hezký víkend!
Zuzka

**Comment by andywaltlova** [comment]
Ahoj,

vůbec není zač, zatím jsi první kdo odevzdal :) 

Taky přeju krásný víkend! 
Andy

**Comment by andywaltlova** [comment]
Zavírám issue, protože je vše splněno, komentovat jde i pod zavřením :)
