### ISSUE TITLE
Další várka :-)

### ISSUE THREAD

**Issue by zopletalova** [zopletalova/python-012021#4]
Ahoj Andy,
@andywaltlova 
posílám první tři programy tohoto týdne (11 - 13).
Tento týden trochu nestíhám, bo minule jsem nebyla na lekci kvůli tech meetupu, v pátek měla kariérní tipy a o víkendu jsem zkusila hackathon.... 😅😅😅 Se to nějak sešlo.
Ale snad to zítra do další lekce nebo krátce po ní srovnám ✌
Předem moc díky za připomínky!
Z.

**Comment by andywaltlova** [comment]
Ahoj, tak to jsi mela co delat teda! na hackathonu jsem te videla :)

### 11. úkol :heavy_check_mark:

- Supr, neni co dodat :)

### 12. úkol :heavy_check_mark: 

- Pěkné !
- Asi bych umazala závorky když vracíš hodnotu v `pujc_auto()`, když vracíš jen jeden string jsou tam zbytečně matoucí. Else vetev je tam vlastne zbytecna, protoze po `return` uz se nic nevykonava, takze kdyz if plati funkce skonci uz na 9 radku, druhy `return` proto muze byt hned na 10 radku. (to jsou jen kosmeticke upravy, nic jineho se u tebe komentovat neda 😄 )
- Prijde mi trochu nezvykle pouzivat `in` operator, kdyz vlastne porovnavas jen dva stringy, `==` by stacilo. `in` ve me totiz budi dojem ze je tech hodnot v `auto1.zn_typ` vice (list, mnozina, tuple, slovnik ...). Funguje to, jde tu jen o citelnost.

### 13. úkol :heavy_check_mark:

> Proč mi prosím nefungovalo
> if auto_p not in auto1.zn_typ or auto2.zn_typ or auto3.zn_typ:
> nebo tak něco?
- protoze kdyz si (pro prehlednost) uzavorkuji jednotlive podminky ktere kontrolujes, vypada to takto:
`if (auto_p not in auto1.zn_typ) or (auto2.zn_typ) or (auto3.zn_typ):`
- prvni zavorka je v pohode, druhe dve vpodstate kontroluji jen jestli je u daneho auta parametr `zn_typ` neprazdny (cokoli neprazdne je `True`, `False` by byla napriklad `0`,`''` jako prazdny string nebo `None`)
- pravdepodobne by si taky chtela aby platily spis vsechny podminky najednou (ani jedno auto se nerovna auto_p) -> `and` misto `or`
- Pri kontrole pomoci `not in` uz je to spravne zapsane :)

Celkově radost opravovat! 👍

**Comment by zopletalova** [comment]
Ahoj Andy,
@andywaltlova 
děkuji za komentáře k předchozím příkladům! 
Ještě na to kouknu - hlavně jak tam píšeš, že se dalo něco zjednodušit. 👍

Jen mě teď rychle napadá, to "in" jsem použila, bo sice uživatel zadával např. "Škoda", a ono je tam "Škoda Octavia" - tak to by se řetězce nerovnaly. Tady mám zn_typ (značku a typ) v rámci jednoho řetězce... Fakt je, že já ty operátory apod. lovím někde náhodně z hlavy z kusých znalostí základů jiných programovacích jazyků, případně SQL, sama tedy někdy nevím, odkud to vlastně mám, takže dobře, že mě nutíš se nad tím zamyslet... :-) Tady mělo být "in" použito ve smyslu "řetězec je obsažen v řetězci" :-) Ale možná to jde vyjádřit i jinak...
 
Odevzdala jsem taky 14. a 15., tak na to prosím koukni, když budeš mít chvilku. 
Přiznám se, že jsem z toho minulého týdne, jak jsem tam nebyla, nestihla udělat příklady z hodiny  ani kouknout na breakout roomy, ale nechtěla jsem moc nabrat zpoždění s domácíma úkolama... 
Aspoň kouknout na ty breakout roomy z minula ale ještě chci, určitě tam bylo něco zajímavýho, nějaké tipy!  👍

Měj se zatím hezky, ještě jednou díky a těším se na další úkoly.
Z.

**Comment by andywaltlova** [comment]
Ahoj, jasne kouknu na to! 
Mas pravdu s tim `in`, nejak jsem prepokladala ze je tam jen ten jeden retezec :) Takze `in` je samozrejme vporadku. 

Tady by se pak asi jedine dalo treba jeste pouzit napriklad `zn_typ.startswith('Škoda')`, ale zase bychom museli předpokladat že mame ten spravny nazev hned nazacatku :)

#### 14. Úkol ✔️ 
- Super, pekne elegantni reseni 👍 
#### 15. Úkol ✔️
- Taky neni co vytknout, napsala jsi to uplne idealne :)

Mas tedy i 3 tyden splnen :)
