### ISSUE TITLE
Čtvrtý týden

### ISSUE THREAD

**Issue by zopletalova** [zopletalova/python-012021#5]
Ahoj Andy,
@andywaltlova 
odevzdávám první úkoly z tohoto týdne. Snad jsem správně pochopila zadání, uvidíme :-)
U toho 17b (složitější varianta) jsem se v tom chvíli docela motala, co vlastně chci, než jsem si řekla, že do toho seznamu uložím celé ty objekty. Jako nevím, jestli je to zrovna elegantní a datově úsporné. 
Asi bych mohla pro tyhle účely z objektu v rámci funkce "zhlédni_položku" do seznamu uložit jen název pořadu a jeho délku trvání  - ale to už by nebyl seznam, ale vlastně slovník, ne? A ta funkce fdelka_sledovani počítající celkový čas by při procházení slovníku sčítala časové hodnoty... Nebo možná i existuje funkce, která ty hodnoty umí sečíst rovnou bez použití cyklu... Ale nebylo by to tak univerzální...
No radši už se v tom teď nebudu vrtat :-)
Díky a zatím
Z

**Comment by andywaltlova** [comment]
### 16. úkol ✔️ 
- Super, neni co dodat 👍 
### 17. úkol ✔️ 
- Obe varianty jsou super.
- v 17b , vubec nicemu nevadi ze davas cele objekty do seznamu, naopak vetsinou se pres ten objekt chces dostat ke vsem informacim o tom objektu, takze vytvaret zvlast popis objektu, ktery uz vlastne ty data ma v sobe je zbytecne :)
- Pokud jde o to secteni minut, ocekavala bych takove reseni, jake mas. Prikladam teda reseni, ktere bych pouzila ja, jedine tak na rozsireni obzoru :)

```python
# Tohle je tvoje
sled_celkem = 0
        for p in self.zhlednute_porady:
            sled_celkem += p.get_celkova_delka()

# rika se tomu list comprehension - zkraceny zapis pro vytvoreni listu
sled_celkem = sum([p.get_celkova_delka() for p in self.zhlednute_porady])
```

**Comment by zopletalova** [comment]
Ahoj Andy,
@andywaltlova 
posílám zbytek úkolů. O víkendu jsem zas měla nějaké Czechitas experimenty, tak jsem dodělávala dnes. Ale sama, jak Jirka skončil svůj výklad, tak jsem se odpojila. Já si na to chci vždycky přijít sama, jinak to nemá cenu 😁
Každopádně někdo by vás měl prohlásit za svatý, za to, jak se nám věnujete!!! 👍
Nad úkolama jsme se tu dnes pobavili - jedenáctiletej syn mi tu přes internet kontroloval kurzy měn, nejvíc ho samozřejmě zajímaly bitcoiny 😀 A pak to teda vypadá, že Faker moc neumí Slováky - John Wood, Jennifer Taylor nebo Justin Jones nezní moc slovensky 😀 Tak tím jsme se tady taky chvíli bavili, kdo všechno bydlí na Slovensku... 😁 Snad není chyba na mém přístroji, respektive v mém kódu 😁
Zatím ahoj a díky moc
Z

**Comment by andywaltlova** [comment]
### 18 ✔️ 
- Parada 👍  
- pripominam jen ze importy je lepsi dat uplne nahoru souboru (importy -> definice funkci a trid -> hlavni kod)
### 19 ✔️ 
- Taky super :) 
### 20 ✔️ 
- Super :) Obecne s cestinou i slovenstinou jsou problemy no, vetsinou je vse delane akorat na anglictinu. Je ale zajimave ze tady si treba nedostatek slovenskych dat kompenzuji ocividne jinym jazykem :)


Týden 4 tedy splněn ! :-)
