### ISSUE TITLE
Pátý týden 

### ISSUE THREAD

**Issue by zopletalova** [zopletalova/python-012021#6]
Ahoj Andy,
@andywaltlova
hlásím, že jsem odevzdala úkoly za tento týden.
Na žádný zásadní problém jsem myslím nenarazila.
Na čem jsem ale ztroskotala, je ten Jupyter Notebook.
Instalovala jsem v PyCharmu, taky na počítači přes příkazový řádek, ale neumím to použít (všude to vypadá, že instalace úspěšně proběhla, ale ani přes ten příkazový řádek se to nechová, jak tam píšou, žádný okno v prohlížeči se neotevře, vypadá to, že se to z nějakého důvodu nepřipojí, nespustí).
Napadlo mě, jestli tomu nechcete případně věnovat chvilku na konzultacích, mně to přijde praktický a zajímavý a kdo si chce hrát s Pythonem, asi by měl umět i s tímhle...
Díky moc a zatím! :-)
Zuzka

**Comment by zopletalova** [comment]
Ahoj, 
tak update - už jsem ten Jupyter Notebook rozchodila. Musela jsem updatovat nějaký ten pip.
Z.

**Comment by andywaltlova** [comment]
### 21 ✔️ 
- Super 👍 
- Jinak pokud chces treba u toho `'Close'` sloupce prvni radek, muzes klidne udelat `first = df.iloc[0,-1]` , kde prvni je index prvniho radku a pak staci -1 pr posledni sloupec, obdobne pro posledni hodnotu posledniho sloupce -> `last = df.iloc[-1,-1]`
- U tech akcii je pak spravne ten pristup kde volas `min` a `max` na celou serii :) (protoze iloc by fungoval jedine kdyby jsi mela data serazena aby si mohla vzit maximum treba z prvniho radku)
### 22 ✔️ 
- Nemam pripominky, presne takto bych si to predstavovala :)
### 23 ✔️ 
- Taky skvele
- jen pozor nepojmenovavej si promenne velkymi pismeny (ty se pouzivaji u objektu)
    - tedy  `DataFrame` -> `dataFrame | data_frame  |  df` (toto je docela caste pojmenovani)
### 24 ✔️ 
- Taky paráda !
### 25 ✔️ 
- Opet skvele :-)

---
Nemam moc co dodat, jen koukam 👀 

Ohledne Jupyter notebooku, bavila jsem se ted s Jirkou a Lidou, pravdepodobne zaradime na pondelni konzultaci ( ne tu co ted bude, ale ten dalsi tyden -> 29.brezna) 15 min nejakeho predstaveni jupyter notebooku - kdy ano, kdy ne apod. Asi se nam to bude hodit i az si budeme vykreslovat nejake grafy :-)

Díky ! Tento tyden mas tedy take hotove 🥳
