### ISSUE TITLE
Půjčovna :-)

### ISSUE THREAD

**Issue by zopletalova** [zopletalova/python-012021#9]
Ahoj Andy,
@andywaltlova 
odevzdala jsem půjčovnu.
Tedy, odevzdala jsem toho víc, než jsem chtěla, a to už před pěti dny a neumím to z Gitu smazat :-)
Ale ta správná půjčovna by měla být tady - funguje :-)
https://github.com/zopletalova/python-012021/tree/main/venv/Scripts/pujcovna
a měla by fungovat.
Jsem teda ráda, že jsem to vůbec zvládla odevzdat, protože jak jsem tam dala Gitignore, tak jsem to neuměla zas zrušit. :-)
Pomazala jsem tudíž všechny Gitignore soubory, který jsem našla, a pak jsem to sem nějak dostala.
Ale budu se muset na ten Github ještě podívat :-)
Na to předchozí, co jsi posílala, ještě pořádně kouknu, díky moc! :-)
Z.

**Comment by andywaltlova** [comment]
Ahoj ! 👋 

Super, zalozene to mas dobre. Koukam ze sis pridala i nejake vlastni css, zarovnani na stred je pekne 👍 
Jinak idealni je odevzdavat zkratka celou slozku projektu, tady mam jen jednu vyhradu ke strukture, kterou tam ted mas. A to hlavne ke slozce `venv`, do ktere by si nemela davat tvuj projekt - ten existuje sam o sobe, ve slozce venv existuje jen to nase virtualni prostredi ktere muzeme(nemusime) pouzit :) Prikladam ocekavanou strukturu slozky s projektem nize. 

Jinak k virtualnimu prostredi je pekny treba [tento clanek](https://towardsdatascience.com/virtual-environments-104c62d48c54) nebo [toto video](https://youtu.be/APOPm01BVrk).

Obsah slozky s projektem by mela vypadat takto:
```
pujcovna/
    pujcovna/
        __init__.py
        settings.py
        urls.py
        asgi.py
        wsgi.py
    katalog/
        migrations/
            __init__.py
        __init__.py
        admin.py
        apps.py
        models.py
        tests.py
        views.py
    db.sqlite3
    manage.py
venv/
    ....

```

Abys vedela jak to kontroluji, tak mam u sebe naklonovany tvuj git repozitar, vzdy kdyz udelas nejakou zmenu, tak ja si ty zmeny stahnu na ten muj lokalni klon a zkusim to spustit :-) Mohla bych klidne pouzit tvoje virtualni prostredi a spustit si to v nem. No pro me je jednodusi mit jedno prostredi ve kterem spoustim vsechny kontrolovane projekty - protoze stejne pouzivame vsichn istejne balicky.

✔️ Jinak body za ukol jsem si poznacila, akorat uprav prosim tu strukturu, az to budes mit upravene, klidne issue zavri :)

**Comment by zopletalova** [comment]
Ahoj Andy, 👋
odevzdávám úkol - už jsem si v těch adresářích konečně uklidila 😁
Díky za materiály k virtuálnímu prostředí. Já to na té předminulé lekci v rychlosti pochopila tak, že chci-li v něm projekt spustit, musím ho mít v tom adresáři venv, teď už chápu, že ten jen slouží k tomu, aby si pamatoval ty podmínky, prostředí, ve kterém se něco (co je umístěné kdekoliv) spouští.
K úkolu mám asi jenom jediný dotaz - nějak se mi v dokumentaci nepodařilo najít field typu Currency, nebo tak něco. 
Není takový v django a nebo jsem něco přehlídla?
Díky a zatím ahoj! 
Z

**Comment by andywaltlova** [comment]
Ahoj,

myslím, že django nemá žádný oficiální Currency field, ale našla jsem [modul](https://github.com/django-money/django-money), který lze doinstalovat a má asi přesně to co si představuješ, dokonce jsem koukala že můžeš nějakým způsoběm i validovat co je přijatelné a co ne. 

Jinak pokud bych to měla udělat v djangu, tak bych vzala asi [DecimalField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#decimalfield) a specifikovala v něm kolik je to maximalne a na kolik desetinnych mist :)
